- cloud-init/daily_deb.sh
The change here makes daily_deb wait until cloud-init is finished
before it starts operating.
We had a very odd failure:
:: adding cloud-init daily PPA
E: Type 'curity' is not known on line 50 in source list
/etc/apt/sources.list
E: The list of sources could not be read.
failed: adding cloud-init daily PPA
The suspected reason is that cloud-init was editing /etc/apt/sources.list
at the same time that the daily_deb script ran 'apt-get update'.
> cloud-init/daily_deb.sh: wait for cloud-init to finish.

- git-ubuntu/vm_setup
Teach vm_setup to install either the snapcraft deb or the snapcraft snap
depending on the option given.
They differ on behaviour and release management. We're having trouble
aligning our CI with "official" builds on Launchpad. We've been advised
to try the edge snap which has some non-determinism removed. And
we're told that Launchpad is expected to switch to the snap eventually.
So permit both so that we can tweak our CI accordingly.
> Add --snapcraft-deb and --snapcraft-snap options

- cloud-init/daily_deb.sh
Bug 1796137 meant that cosmic containers were not booting in the
default 30 seconds.  The change here just waits up to 120s for the
container to boot before using it.
> cloud-init/daily_deb.sh: wait 120s for boot of container.

- cloud-init/copr_build.py
- cloud-init/copr_test
Disable the epel-6 build and enable the `baseurl` repository when using an http proxy.
> Fix the Copr build and test scripts

- boot-speed/testflinger/test_cmds.sh
Changes:
- retry to `snap refresh` if the change status is 'Error'
- test_cmds.sh: always double quote around variables (SC2086)
> bootspeed: make the measurement scripts more robust

- cloud-init/copr_test
In this way we'll be using only the baseurl, which is the only mirror we
can reach from the Jenkins hosts, and we should see less failures.
> copr: disable the mirrorlist when running copr_test

- cloud-init/daily_deb.sh
apt-add-repository sometimes fails because of GPG keyserver timeouts
or networking problems. Retry the command 10 times at exponentially
spaced intervals.
> cloud-init: daily_deb.sh: retry apt-add-repository

- boot-speed/testflinger/measure-device.sh
The change will make things easier to handle on the Jenkins side.
> bootspeed: make measure-device.sh work independently of the CWD

- boot-speed/clouds/measure-cloud.py
The image ID (ami-*) was incorrectly logged instead.
> bootspeed ec2: fix the logging of the image serial

- boot-speed/clouds/measure-cloud.py
* workaround LP: #1832386 by pulling images from the 'releases' stream
for Xenial and Bionic on EC2 A1 instances
* drop the cloud2serial() function and switch to pycloudlib's newly
implemented image_serial() function, which also handles images from the
'releases' stream.
> bootspeed: workaround LP: #1832386

- boot-speed/testflinger/dragonboard410c-core18.provision.yaml
- boot-speed/testflinger/measure-device.sh
- boot-speed/testflinger/rpi3b-core18.provision.yaml
Changes for devices:
* pull the Core18 beta images when testing devices
* name the files with a timestamp up to the second (like for the clouds)
* print the testflinger yaml file before submitting it (for debugging)
"current" Core16 beta images are not available yet.
> bootspeed: use the Core18 beta images, plus minor improvements

- boot-speed/clouds/ec2_cleanup.py
- MAX_EC2_INST_AGE: cast to int
- Use a set for stale_instances
- break the inner for loop after the first 'Name' tag matching
'bootspeed-*' is found
- Retry wait_until_terminated() once if it fails
- Nicer script output
> ec2_cleanup: improve the script logic

- boot-speed/bootspeed.sh
- boot-speed/clouds/.gitignore
- boot-speed/clouds/measure-cloud.py
- boot-speed/testflinger/measure-device.sh
Other minor changes:
- EC2: add command line parameters to specify the SSH keypair to use
- devices: bump the testflinger timeout to 16h
- all: do not call `systemd-analyze plot`
- all: add a .gitignore
> bootspeed: add support for LXD and KVM instances

- boot-speed/bootspeed.sh
This reverts commit 841f1b672828ff7a5d7de4865853159844499f98.
The collection of the `systemd-analyze plot` SVGs was disabled because
they often take more space than all the other measurement artifacts
combined, and we are not immediately using them. However it may be
worth collecting them to ease the analysis of the boot process.
> Revert "bootspeed.sh: do not call `systemd-analyze plot`"

- cloud-init/copr_build.py
Changes:
- use epel-8-x86_64 as the test chroot
- increase the wait time before checking the build tasks
> cloud-init copr: the main build target OS is now CentOS 8

- cloud-init/copr_build.py
Sometimes 3 minutes are not enough for the COPR infrastructure to show
the list of chroots cloud-init is being built in. Bump the sleep time
to 5 minutes.
> Sleep more before checking the cloud-init copr tasks

- ubuntu-advantage-client/ec2_cleanup.py
This script cleans up vms, vpcs, security groups and images.
It will be called by a jenkins job running on torkoal per the following PR:
https://github.com/canonical/server-jenkins-jobs/pull/134
> uaclient: add helper script for ec2 cleanup of stale VMs and images

- ubuntu-advantage-client/azure_cleanup.py
This script cleans up all resource associated with a resource group associated with a given tag.
It will be called by either a travis job at the end of each test run or through a separate daily jenkins job.
> uaclient: add helper script for azure cleanup

- ubuntu-advantage-client/ec2_cleanup.py
Allow the ability to pass --before-date parameter to ec2_cleanup.py to allow CI jobs to delete
any resource older than MM/DD/YY.
The --before-date param can take to format MM/DD/YY
To test:
```
pip3 install boto3
AWS_ACCESS_KEY_ID=<yours> AWS_SECRET_ACCESS_KEY=<your_key> python3 ubuntu-advantage-client/ec2_cleanup.py  -t uaclient-ci-* --before-date 08/11/20
```
> ua-client: ec2_cleanup add --before-date param to remove stale items

- cloud-init/copr_test
When using an http proxy make sure to disable all the dynamic mirror
URLs. In particular:
- Uncomment the baseurl in /etc/yum.repos.d/*.repo.
- Comment out the mirrorlist and metalink URLs in *.repo.
- Replace the dynamic download.fedoraproject.org host with
dl.fedoraproject.org, which is static.
- Run the above as part of the install_pkgs() function, as installing
packages may add new repos (e.g. EPEL).
- Stop disabling fastestmirror, not needed when doing the above.
This is similar to:
https://github.com/canonical/cloud-init/commit/d4639837ff623f199afd3e44aa836bf4b845456e
> copr_test: always disable non-baseurl mirrors when using a proxy

- ubuntu-advantage-client/azure_cleanup.py
Right now, we are trying to use the `azure_cleanup` script in uaclient. However, this scrips was coded with the intention of removing all of the `resource_groups` at the end of all tests. Currently, we intend to run this script after each test has finished. To do that, we must updated how we perform the tag matching in this script
> Update azure_cleanup script

- lma-integration/docker-compose.yml
The OCI images used previously were hosted in some personal DockerHub
accounts, now they were migrated to a not official Server team account.
> LMA stack: update docker-compose.yml to use the team's OCI images

- cloud-init/copr_build.py
Allows to specify a custom project id. May be useful for running builds
outside of the usual cloud-init and cloud-init-dev copr projects.
> copr_build: syntax change: add --project, --required-chroot, drop --srpm

- lma-integration/docker-compose.yml
Launchpad push rules are all set to publish images in our DockerHub
squeakywheel account. For now, the tag for all the images is 'edge'.
> LMA: update tag of OCI images, now all of them are published by LP

- lma-integration/tests/cortex_test.sh
The 'runtime-config' excerpt shows up in the output of
'$cortex_url/services' when we invoke cortex using the
'--runtime-config.file' option.  The runtime config file is something
we can provide to the cortex binary that allows us to change the
service configuration on-the-fly.
At the moment, we do not start cortex using this option.  For this
reason, it doesn't make sense for us to try to grep for this option in
the output.  This commit removes the grep, which makes the test
finally pass 100%.
> LMA: Don't grep for 'runtime-config' on cortex_test.sh

- oci-unit-tests/postgresql_test.sh
This commit is based on Andrea's suggestion from PR #60.  Instead of
relying on the host's psql binary, we can (and indeed should!) use the
container's psql.  This has a bunch of positive points:
- It makes it unnecessary to install test dependencies on the host.
- It exercises the psql from inside the container, which is software
that we will ship to the users anyway.
- It uses non-localhost hostnames for the tests (albeit we'd still
be using a local docker network bridge).
The only "drawback" (if you can say so) is that it's not really
feasible to use here-document when invoking psql anymore, but this is
really not very significant for our purposes.
I've made sure the tests are still passing, and I don't have psql
installed in the host machine.
> OCI unit tests: Use psql from container

- oci-unit-tests/redis_test.sh
This commit creates the unit tests for the redis OCI image.  It is
based on the postgresql unit tests, but with some
modifications/improvements.
Currently, it tests:
- A simple connection to a redis-server container without a password;
- A simple connection to a redis-server connection with a password;
- Insertion/retrieval of values to/from a redis-server container;
- Persistent volumes used with redis-server containers.
This is a good start, and we should work towards writing more tests
later.
> OCI unit tests: redis

- oci-unit-tests/helper/test_helper.sh
- oci-unit-tests/mysql_test.sh
This commit implements the unit test for mysql.  It is loosely based
on the postresql unit test, but has a few important modifications:
- It was necessary to extend the 'wait_container_ready' helper
function and make it accept an optional argument specifying the
timeout.  mysqld takes a long time to start.
- I took the opportunity and also extended 'stop_container_sync' to
take an optional timeout as its second argument, although it's not
being used so far.
- The unit test was written using the same idiom I used for the redis
unit test (with functions that encapsulate the execution of both the
server and CLI programs).
Because the mysql server takes a long time to start, running all of
the tests will also be time-consuming.  I'm also not entirely
confident that a 60-second timeout to …
> OCI unit test: mysql

- oci-unit-tests/helper/test_helper.sh
5 seconds are very often not enough, at least not on busy Jenkins nodes.
Let's bump it to a default that will work most of the time while also
being reasonably low.
> oci test_helper: bump the container timeout to 30s

- oci-unit-tests/prometheus_test.sh
The following scenarios are tested:
- Call prometheus via command line.
- Check if the default target is up on online as it supposed to be.
- Check if data is persisted between containers destruction when using a
docker volume. In this scenario passing a custom config file as a
parameter was also exercised.
> OCI unit test: prometheus

- lma-integration/README
- lma-integration/config/alertmanager.yml
- lma-integration/config/cortex.yaml
- lma-integration/config/grafana/provisioning/datasources/datasource.yml
- lma-integration/config/prometheus.yml
- lma-integration/config/telegraf.conf
- lma-integration/docker-compose.yml
- lma-integration/run-tests
- lma-integration/tests/Dockerfile
- lma-integration/tests/alertmanager_test.sh
- lma-integration/tests/globals.sh
- lma-integration/tests/helper/test_helper.sh
- lma-integration/tests/telegraf_test.sh
- lma-integration/tests/tests.sh
This series of commits implement the "test containerization" idea that
Lucas told me about.
The gist of it is that the tests will now be executed from inside
another container (which is part of the docker-compose group of
containers), which means that all the communication between the
containers (and therefore the services) will take place using the
internal network that docker-compose will create, instead of
localhost.
It took me some time to adjust the scripts and make them properly
print only the test results.  In the end, I think I've reached a
compromise that is decent enough while avoiding printing too much
pollution from logs.  Here's the full output when you invoke
`./run-tests.sh`:
```
Waiting until the test container becomes available...
Creating network …
```
> LMA: Containerize the test infrastructure

- oci-unit-tests/alertmanager_test.sh
- oci-unit-tests/apache2_test.sh
- oci-unit-tests/cortex_test.sh
- oci-unit-tests/memcached_test.sh
- oci-unit-tests/mysql_test.sh
- oci-unit-tests/nginx_test.sh
- oci-unit-tests/postgresql_test.sh
- oci-unit-tests/prometheus_test.sh
- oci-unit-tests/redis_test.sh
- oci-unit-tests/telegraf_test.sh
In a discussion with Paride, we noticed that the OCI images can become
stale and are not automatically updated when there is a new version
available.  For this reason, it's better to call "docker pull
$DOCKER_IMAGE" every time we're starting a unittest.
> OCI unit tests: Make sure we're using the latest OCI image

- ubuntu-advantage-client/azure_cleanup.py
Otherwise we hit console output timeouts like the following:
https://travis-ci.com/github/canonical/ubuntu-advantage-client/jobs/439263319#L687-L691
> azure_cleanup: flush the output stream in emit_dots stream to print during travis

- oci-unit-tests/helper/test_helper.sh
- oci-unit-tests/telegraf_test.sh
- oci-unit-tests/telegraf_test_data/telegraf.conf
The telegraf unit test is unfortunately broken due to the way
assertTrue is being called.  I discovered this because the telegraf
OCI image was not configured by default to export the prometheus data
via its localhost:9273/metrics endpoint.
I fixed the image, and now I'm fixing the tests.  I'm also
implementing the idea discussed with Paride, which is to make
"wait_container_ready" accept a fourth argument allowing the caller to
grep for $msg in the full log message, and not only in the last line
of the log.
Last, but not least, I added descriptive messages to the assertTrue
tests.
> OCI unit test: fix telegraf test

- ubuntu-advantage-client/lxd_cleanup.py
Bionic is the release used on some of our Jenkins nodes.
Because of that, we need to make our scripts run on
python 3.6. This PR fixes that issue for the lxd cleanup script
> Make lxd_cleanup script run on python 3.6

- oci-unit-tests/alertmanager_test.sh
- oci-unit-tests/apache2_test.sh
- oci-unit-tests/cortex_test.sh
- oci-unit-tests/grafana_test.sh
- oci-unit-tests/memcached_test.sh
- oci-unit-tests/mysql_test.sh
- oci-unit-tests/nginx_test.sh
- oci-unit-tests/postgresql_test.sh
- oci-unit-tests/prometheus_test.sh
- oci-unit-tests/redis_test.sh
- oci-unit-tests/telegraf_test.sh
The mysql_test.sh script didn't work due to some syntax errors in HERE-docs; these are repaired and the operations refactored to simplify them by introducing a docker_mysql_execute() routine that takes a SQL string.  I opted to pass override parameters like MYSQL_USER via local env variables, as I found them reasonably convenient and self-documenting; there's other ways to handle this so if you don't like it we can use a different approach.
(I notice the postgresql test could use a similar refactoring, but left that as is to keep this PR more focused on the mysql test.)
The test was also failing due to starting before the mysql database service was fully ready; thank you for diagnosing that to needing to watch for the port number.  This includes that fix.
Some of the messages used with …
> Mysql test cleanup

- oci-unit-tests/alertmanager_test.sh
- oci-unit-tests/apache2_test.sh
- oci-unit-tests/cortex_test.sh
- oci-unit-tests/grafana_test.sh
- oci-unit-tests/memcached_test.sh
- oci-unit-tests/mysql_test.sh
- oci-unit-tests/nginx_test.sh
- oci-unit-tests/postgresql_test.sh
- oci-unit-tests/prometheus_test.sh
- oci-unit-tests/redis_test.sh
- oci-unit-tests/telegraf_test.sh
The test scripts are still using the "squeakywheel/" namespace, which
was just a temporary place to test the images.  This commit updates
the scripts to test the actual released images.
> OCI: Use the "ubuntu/" namespace to test the images

- oci-unit-tests/alertmanager_test.sh
- oci-unit-tests/apache2_test.sh
- oci-unit-tests/cortex_test.sh
- oci-unit-tests/grafana_test.sh
- oci-unit-tests/helper/common_vars.sh
- oci-unit-tests/memcached_test.sh
- oci-unit-tests/mysql_test.sh
- oci-unit-tests/nginx_test.sh
- oci-unit-tests/postgres_test.sh
- oci-unit-tests/prometheus-alertmanager_test.sh
- oci-unit-tests/prometheus_test.sh
- oci-unit-tests/redis_test.sh
- oci-unit-tests/telegraf_test.sh
Changes:
- oci: fully parametrize the OCI image to test
- oci: add missing shellcheck directives
- oci: make all the scripts shellcheck-clean
> oci: parametrize and cleanup the tests

- git-ubuntu/vm_setup
Now that we're building on core20 based on a deb, much of the complexity
here can disappear. The base image is switched to Focal. snapcraft is
now always a snap, and so is lxd. The updated tests rely less on the
environment so git no longer needs configuring first.
> git-ubuntu: refactor for core20 base

- oci-unit-tests/apache2_test.sh
The apache2 unit test is using $PWD when composing the path for the
configure files to be mounted inside the container.  This doesn't work
when we're running these tests from an external directory.  We should
use the same pattern we're using to source the helper scripts here,
with the addition of calling "realpath", which is necessary because
docker requires that mount paths be fullpaths.
> OCI: Fix apache2 configure loading

- ubuntu-advantage-client/gcp_cleanup.py
The parsing for gcp cleanup script is incorrect. It is parsing the month part of the string as minutes. We are now fixing that
> Fix gcp cleanup

- oci-unit-tests/helper/common_vars.sh
- oci-unit-tests/standalone-checks_test.sh
**NOTE: This is currently a WIP**
I've decided to take a stab at implementing the test to verify whether
all supported architectures of an image have been properly published.
I don't know if this is the best way to implement this; sometimes I
think it is, other times I think it would be better to write this test
in its own file.
The reason I chose to write this as a helper function (which then
means that it will have to be called by every `*_test.sh` script) is
because we are going to have the test matrix which will cover all
registries x all namespaces x all tags anyway, so why don't take
advantage of that?  But again, this could very well be placed in its
own test file; a benefit is that we can then write generic tests for
all images there (for example, another test that I'm writing now …
> WIP: OCI: Test if all supported architectures have been published

- oci-unit-tests/helper/common_vars.sh
- oci-unit-tests/standalone-checks_test.sh
This commit implements a new test whose purpose is to assert that the
hashes for a certain image-arch-tag combination are equal across all
supported registries.
The idea is simple, but the implementation is a bit involved because
of the many corner cases I've had to deal with.
This test is making certain assumptions.  For example, it is
assuming that all supported architectures have been properly published
in all registries; if it notices that this is not the case, then it
errors out.  It is also only testing images from the "ubuntu"
namespace, because that's the only one that is published on both
registries.
Unfortunately, like the test to check if all supported architectures
are available, this test is also currently failing due to the problem
with our s390x 21.04 images.
> OCI: Assert that image hashes are equal across registries

- oci-unit-tests/helper/common_vars.sh
Ref.: https://bugs.launchpad.net/bugs/1930094
The official architecture name that Docker uses is "ppc64le", not
"ppc64el".
> OCI: Use "ppc64le" as the arch name

- oci-unit-tests/apache2_test.sh
- oci-unit-tests/cortex_test.sh
- oci-unit-tests/grafana_test.sh
- oci-unit-tests/helper/test_helper.sh
- oci-unit-tests/memcached_test.sh
- oci-unit-tests/mysql_test.sh
- oci-unit-tests/nginx_test.sh
- oci-unit-tests/postgres_test.sh
- oci-unit-tests/prometheus-alertmanager_test.sh
- oci-unit-tests/prometheus_test.sh
- oci-unit-tests/redis_test.sh
- oci-unit-tests/telegraf_test.sh
When running a test whose image cannot be downloaded from the
registry, docker will use the cached image (from a previous run).  In
order to prevent this misleading scenario from happening, this commit
forces the removal of an existing image before we start testing.
Note that we just remove the image if `"${DOCKER_IMAGE}"` (which
contains the full image spec) starts with `"${DOCKER_REGISTRY}"`.  This
is necessary in order to continue supporting testing locally built
images.
> OCI: Remove previous image before starting test

- oci-unit-tests/prometheus_test.sh
The version of prometheus that's being delivered in our OCI image has
updated their web interface and are now making extensive use of
JavaScript; it actually *requires* JavaScript now, so a simple "curl"
won't be able to obtain useful information from the pages.
Our test was written for a previous version of prometheus, which
worked fine with "curl".  Fortunately, upstream has kept the "classic"
interface around, so it's still possible to query the pages we need
using it.
Of course, there's the question of how long upstream will be willing
to maintain the classic interface.  We might have to revisit this
later, but for now it works.
> OCI: Use "classic" interface when querying prometheus' endpoints

- oci-unit-tests/nginx_test.sh
Docker's IPv6 network support isn't very trivial to set up.
It's possible to enable IPv6 on the bridge that is used by all images
by default, and that works OOTB; however, having IPv6 support on
"docker network create" is a bit more involved and requires us to
provide a "--subnet" argument to the command.
Instead of messing with arguments, I suggest that the nginx unit test
doesn't create its own network, and instead rely on the host network,
like the apache2 unit test does (this was Athos' original suggestion
from the beginning, btw).
I think it'd be great to have every test running on its own isolated
network, but until we have a better way to fire them up with IPv6
support I don't see an easy way to overcome this problem.
> OCI: Don't create a network on nginx_test.sh

- oci-unit-tests/prometheus_test.sh
The prom/pushgateway image is not published for all architectures that
are supported by us.  For this reason, when we run the test on those
architectures (for example, s390x), it fails.
In order to avoid such failures, this commit implements skipping of
tests that use the prom/pushgateway image on non-amd64 architectures.
> OCI: Skip testing with prom/pushgateway on non-amd64 arches

- oci-unit-tests/standalone-checks_test.sh
Currently we print a message tagged as "error" when there is a
mismatch between the number of images available in one registry and
another.  We also print a misguided message saying that the test will
be aborted, when in fact it is not.
This message can be just a warning, since it doesn't actually impact
the actual test.
> OCI: Adjust message when number of images differ between registries

- ha/virsh/delete-cluster.sh
- ha/virsh/setup-cluster.sh
- ha/virsh/vm_utils.sh
The proposed changes add a `--iscsi` option to `setup-cluster.sh`, it will create a separate VM to be used as an iscsi target (in the future it could be used for other external services) and configure all the cluster nodes as iscsi initiators. If this new option is not passed to the script the old behavior will be the same.
If you want to test you can run `setup-cluster.sh --iscsi`, ssh into any cluster node and check if the iscsi block device is there:
```
ubuntu@fence-test-virsh-impish-node01:~$ sudo lsblk --scsi
NAME HCTL       TYPE VENDOR   MODEL         REV SERIAL                               TRAN
sda  6:0:0:0    disk LIO-ORG  iscsi-disk01 4.0  2f87b5b9-7f8a-49d3-9f85-d917a48c5c66 iscsi
ubuntu@fence-test-virsh-impish-node01:~$ cat /proc/partitions 
major minor  #blocks  name
7 …
```
> HA: iscsi setup

- ha/virsh/delete-cluster.sh
- ha/virsh/run_tests.sh
- ha/virsh/vm_utils.sh
It allows parallel executions of the tests by the Jenkins jobs.
This is the implementation of what was described here: https://github.com/canonical/server-jenkins-jobs/pull/199#issuecomment-868529993
> HA: rename VMs name, define the name based also on the agent name

- ha/virsh/create-vm.sh
This reverts commit 1a438f342615bfb96595ae7cba081b2b55a9953f.
The new fence-agents package is already in impish-proposed.
> Revert "Temporarily add my PPA to install the new fence-agents package"

- ha/virsh/run_tests.sh
- ha/virsh/tests/resource_systemd_test.sh
Those changes were tested in `dugtrio` and also in my host running Focal, everything seems to be working fine for me.
> HA: fix curl calls in systemd resource agent tests

- oci-unit-tests/cassandra_test.sh
- oci-unit-tests/cassandra_test_data/Dockerfile
- oci-unit-tests/cassandra_test_data/hello-cassandra.cqlsh
This new test suite includes a Dockerfile so an image with cqlsh is
built when the tests are running so we can perform simple transactions
in Cassandra
Signed-off-by: Athos Ribeiro <athos.ribeiro@canonical.com>
> OCI: Add Cassandra tests

- ha/virsh/tests/fence_scsi_test.sh
I ran this test 5 times in sequence in `dugtrio` with the proposed patch and it passed in all the attempts.
> HA: wait more time to get the node offline in the fence-scsi test

- ha/virsh/create-vm.sh
- ha/virsh/delete-cluster.sh
- ha/virsh/setup-cluster.sh
- ha/virsh/tests/fence_scsi_test.sh
- ha/virsh/tests/fence_virsh_test.sh
- ha/virsh/tests/resource_ipaddr2_test.sh
- ha/virsh/tests/resource_lvm-activate_test.sh
- ha/virsh/tests/resource_systemd_test.sh
- ha/virsh/vm_utils.sh
This is a preparation to test the multipath fence agent. To have a minimal multipath setup we need at least 2 network interfaces in each node so that we can reach the target via different paths.
With that said, I added changes to create a new network using virsh and added it to all VMs. The only thing that I did not figure out how to fix it properly is to get an IP address in this second network interface, at the moment I am calling `dhclient` to assign an IP address to it, if you have a better solution for that, I'll be happy to incorporate to this PR.
And I also ran all the tests locally using this branch and all of them passed.
> HA: add an extra network interface to all VMs

- oci-unit-tests/apache2_test.sh
- oci-unit-tests/cassandra_test.sh
- oci-unit-tests/cortex_test.sh
- oci-unit-tests/grafana_test.sh
- oci-unit-tests/helper/test_helper.sh
- oci-unit-tests/memcached_test.sh
- oci-unit-tests/mysql_test.sh
- oci-unit-tests/nginx_test.sh
- oci-unit-tests/postgres_test.sh
- oci-unit-tests/prometheus-alertmanager_test.sh
- oci-unit-tests/prometheus_test.sh
- oci-unit-tests/redis_test.sh
- oci-unit-tests/telegraf_test.sh
Athos has recently worked on (and fixed) a bug on the golang manifest
generator script which rendered empty manifest files for some images.
Apparently this bug has silently crept in some time ago, and we didn't
notice.  I thought that it'd be useful to expand our current
"is-the-manifest-file-present" unit test and make it also error if the
manifest file is empty (which should never happen).
I wasn't entirely sure whether this should be a new test or not, but I
think it makes sense (and is cleaner) to do it in the existing test.
> OCI: Check whether the manifest file(s) is(are) empty

- oci-unit-tests/cassandra_test.sh
Do not `docker run` in interactive mode (drop the `-i`) but do allocate
a tty (`--tty`) so we can get stdout from the run command.
> oci cassandra: do not `docker run` in interactive mode

- oci-unit-tests/cassandra_test.sh
- oci-unit-tests/cassandra_test_data/Dockerfile
Let's use the official Cassandra image as a source for the cqlsh CLI application. In case the image is not available for a given platform, we then fallback to building a cqlsh image locally. This is a compromise between saving CI resources when possible and still ensuring we will have an image with cqlsh to test Cassandra.
This fixes the tests for Cassandra in s390x, where upstream cassandra images are not available.
> OCI: Fallback to local cqlsh builds

- oci-unit-tests/cortex_test.sh
Upstream has changed the log output of cortex's table manager
component, so we have to adjust the existing unittest to stop
expecting table-related strings in the log.
This has been tested with the upcoming 21.10 cortex OCI image as well
as with the existing images from the ubuntu namespace.
> OCI: Update cortex unittest to reflect changes in the last upstream version

- oci-unit-tests/squid_test.sh
- oci-unit-tests/squid_test_data/cache_config/squid.conf
- oci-unit-tests/squid_test_data/custom_config/squid.conf
This is the initial state of the new squid OCI tests. The first configuration file is just the concatenation of the default Ubuntu configuration files with the docs stripped out. The second, is just a minimal configuration file to ensure we can inject configuration into the image.
> OCI: Add squid tests

- oci-unit-tests/README.md
- oci-unit-tests/bind9_test.sh
- oci-unit-tests/helper/test_helper.sh
- oci-unit-tests/memcached_test.sh
This adds some basic test cases for the new impish bind9 OCI image.  It does a local check that the service is present on the expected port, and a client/server test to check a trivial dns lookup.  This provides a similar level of coverage to what is available in the bind9 DEP8 tests.
Note that due to LP: #1943049 the bind9 image can't be built for impish, so I've been testing against a hirsute-built image.
Testing is performed via:
DOCKER_IMAGE=test/bind9:edge sh ./bind9_test.sh
I also propose making a couple functions as helpers.  These are broken out as separate follow-on commits that can easily dropped or moved to other branches if desired.
> Bind9 tests

- ha/virsh/run_tests.sh
The delete-cluster.sh scripts needs to know the AGENT being tested in
order to construct the VM_PREFIX to cleanup. This is known only within
the for loop iterating over TESTS. Move the delete-cluster.sh call
there.
> ha run_test: do the pre-run cleanup when the AGENT is already known

- ha/virsh/tests/resource_lvm-activate_test.sh
The test is racey with a 1s sleep; seems stable with 3s.
> ha lvm-activate: bump sleep in test_move_resource

- oci-unit-tests/cassandra_test.sh
- oci-unit-tests/cortex_test.sh
- oci-unit-tests/grafana_test.sh
- oci-unit-tests/helper/test_helper.sh
- oci-unit-tests/prometheus-alertmanager_test.sh
- oci-unit-tests/prometheus_test.sh
- oci-unit-tests/telegraf_test.sh
This will break tests for the following images, which need fixing:
- cassandra
- cortex
- grafana
- prometheus
- prometheus-alertmanager
> oci: Verify required manifest files presence

- oci-unit-tests/cassandra_test.sh
- oci-unit-tests/cassandra_test_data/Dockerfile
cqlsh is used to test the published Cassandra images. We currently do so
with the development version of cqlsh. This patch changes this behavior
to use a release version of cqlsh to avoid development issues with the
project builds.
Signed-off-by: Athos Ribeiro <athos.ribeiro@canonical.com>
> oci: build cqlsh image from a release tag

- oci-unit-tests/bind9_test.sh
* LP: #1955680
The dig call should perform some query (it should return 0 even if the query cannot be resolved) in the bind9 server.
> oci: fix dig call in bind9 network tests

- oci-unit-tests/bind9_test.sh
* Check if bind9 accepts connections for both TCP and UDP
* Use ss instead of lsof to leverage installed package (faster tests)
* remove redundant default port from dig call
> Fix bind9 local port tests

- oci-unit-tests/bind9_test.sh
- oci-unit-tests/grafana_test.sh
Some of our assertions will fail silently. These patches fix the issue for bind9 and grafana
> oci: provide assertion error data

- oci-unit-tests/memcached_test.sh
- oci-unit-tests/prometheus-alertmanager_test.sh
- oci-unit-tests/prometheus_test.sh
This set of patches completes the work on always returning helpful error messages when test failures occur.
> oci: describe assertion errors

- cloud-init/copr_test
Switching to Streams requires enabling EPEL-Next, which contains
EPEL packages rebuilt on Streams, see [1].
[1] https://docs.fedoraproject.org/en-US/epel/
> c-i copr_test: run tests on CentOS Streams

- .gitignore
- ha/virsh/create-vm.sh
- ha/virsh/run_tests.sh
- ha/virsh/setup-cluster.sh
- ha/virsh/tests/fence_ipmilan_test.sh
Add some basic tests for `fence_ipmilan`. To do that `ipmi_sim` (provided by `openipmi`) was used to simulate IPMI and do not need real hardware with that feature. In order to make it simple, its tests run in a single VM and not in a corosync/pacemaker cluster, calling `fence_ipmilan` directly.
> Test fence_ipmilan

- oci-unit-tests/loki_test.sh
This PR adds the unit tests for the loki ROCK image.  The first test
is a very simple one; it just makes sure that we can start the loki
service without any configuration changes.  The second test is a bit
more involved: it sets up a promtail service that will be responsible
for monitoring the logs under `/var/log/*.log` and sending them to a
loki service that's running in another container.
These tests should be enough to do cover the basic set of features
from loki.
> OCI: Add loki unit test

- ha/virsh/tests/fence_sbd_test.sh
I was mistakenly using `external/sbd` but that is not the agent that was
promoted to main, the correct one is `fence_sbd`.
> HA: use fence_sbd instead of external/sbd in the test

- ha/virsh/tests/fence_ipmilan_test.sh
Now that the agent was promoted to main we can install only `fence-agents-base`.
> HA: use fence-agents-base instead of fence-agents in fence_ipmilan test

- cloud-init/copr_test
New flags:
--name: allows to specify the container name from the command line
--vm: use a LXD VM instead of a container.
> copr_test: new flags: --name, --vm (SC-989)

- oci-unit-tests/kafka_test.sh
We're hitting the 5000ms timeout in automation.
> oci kafka: bump timeout in "consuming test message"

- oci-unit-tests/standalone-checks_test.sh
We've recently transferred the ownership of the ROCK-related git
repositories from `~canonical-server` to `~ubuntu-docker-images`.  This
commit adjusts the `git clone` command on
`oci-unit-tests/standalone-checks_test.sh` to reflect that.
> OCI: Adjust git clone URL for "utils" repository

- ubuntu-advantage-client/azure_cleanup.py
We have updated the version we use for the Azure API in pycloudlib. This new API has new method for deleting resource groups. We are fixing the script to call the right method.
> Fix delete call for azure resource groups

- ubuntu-advantage-client/lxd_cleanup.py
As part of the rename of UA to pro, we're changing the prefix of behave lxd instances for the pro client integration tests.
This is happening here: https://github.com/canonical/ubuntu-advantage-client/pull/2303
I'm not sure where this script is called. Because the prefix can be overridden, we should make sure any place we call this script is calling it correctly as well.
> cleanup: update lxd prefix for pro client behave

- metric-server-simple/data2influx.py
- metric-server-simple/metric-server-simple.sh
This is needed as a lessons learned from checking the results.
> metric: add more disk and package info

- metric-server-simple/metric-server-simple.sh
Most early stage measurements can run before installing dependencies like hyperfine. Therefore move them to not be seen e.g. in disk or package statistics.
> metric: Run most early measurements before adding dependencies

- ubuntu-advantage-client/gcp_cleanup.py
Since we had a problem with the cleanup of old gcp instances, we are now cleaning up any active instance that is running for more than two weeks
> gcp: delete active instances older than two weeks

- oci-unit-tests/memcached_test.sh
Before libmemcached 1.1.0 the  memccat CLI would not crash in case a key was not provided, but would crash if an empty key was passed. This behavior was changed to crashing when not providing a key and not crashing when an empty key is provided since 1.1.0. Therefore, we test both cases to ensure this test is compliant to all supported libmemcached versions.
> oci: add support for libmemcached >= 1.1.0

- oci-unit-tests/squid_test.sh
This may cause a test failure in any situation where this volume cannot be removed. Since we are using the volume name, which aims this specific test, it should be safe to go for a forced removal.
> oci: force volume removal for squid tests

- metric-server-simple/metric-server-simple.sh
Hopefully with help avoiding 'dataset is busy' errors, which sometimes
go away by waiting.
> metric-server-simple: use longer lxc delete retry backoff

- cloud-init/subiquity_live_server.py
Add subiquity_live_server.py to test live server and live desktop isos
with autoinstall userdata on KVM.
This script performs the following:
- download and cache either Live Server or Desktop ISOs
- creates a cloud_localds seed img with autoinstall user-data
- launches live iso with autoinstall data, allow system to install
- reboot target.img without auoinstall user-data 
- assert cloud-init was error free in both ephemeral and first boot
> cloud-init: add subiquity live iso autoinstall testing

- metric-server-simple/metric-server-simple.sh
LXD by default does not spawn a login shell, but that is required to get a systemd user scope session.
Without a login shell the context is missing and this will fail with `Failed to connect to bus: No medium found`
> metric-server-simple: fix service-security

- metric-server-simple/metric-server-simple.sh
Sometimes a rare event might happen that is hard to recerate and debug later. So far we have seen two times that service startup was bad.
Therefore it would be very helpful to have at least the general final status of all services in the log as it might indicate what was broken.
> metric-server-simple: gather service status

- metric-server-simple/metric-server-simple.sh
If nonzero we want to continue gathering the rest of the data.
> metric-server-simple: ignore RC of systemd-analyze calls

- metric-server-simple/metric-server-simple.sh
The RC of systemctl status --all can easily be non-zero while not being fatal for the system or the metric run. Ignore that to not run into retries (wasting time) and then giving up eventually.
Fixes: 7f331de8
> metric-server-simple: ignore RC of combined service status

- metric-server-simple/metric-server-simple.sh
The || true recently added did break the redirection which no more is capturing the output of systemd-analyze. Since `true` has no output the file isn't created at all and breaks the import.
Change the order so that the output of systemd-analyze is redirected.
Fixes: f444e6e9
> metric-server-simple: fix status redirect

- metric-server-simple/data2influx.py
- metric-server-simple/metric-server-simple.sh
/var/cache/apt can fluctuate a lot depending on how many packages might need to be updated as (relative to the daily image) to install packages of the workload. We are not interested in those fluctuations as they would auto-clean over time anyway.
Therefore run `apt clean` after installing packages for the loaded stage, but we want to know the initial image size if e.g. a clean was forgotten on build, so do not clean it there.
> metric-server-simple: do not trace flaky cache values

- metric-server-simple/metric-server-simple.sh
Since the changes to the mantic minimal image this OOM crashes. On one hand that increase was worth to know about, but on the other hand all the data we get since then is flaky at beast.
While this change itself might shift values a bit, they will at least be more reliable again. The intention is to consider reverting  this change once [1][2] are resolved.
[1]: https://warthogs.atlassian.net/browse/CPC-2985
[2]: https://bugs.launchpad.net/cloud-images/+bug/2032933
> metric-server-simple: increase VM size

- openssh-ccache-check/README.txt
- openssh-ccache-check/openssh-ccache-check.py
This move was happening in parallel with the previous PR, but was done just now. I tested the new testing PPA and recipe, and it's good to go.
> openssh-ccache-check: Update testing PPA path

- openssh-ccache-check/openssh-ccache-check.py
Implement suggestion from https://github.com/canonical/server-jenkins-jobs/pull/287 to exit with 99 (the unstable-return code we have in there) when there is action needed, but the script worked fine otherwise.
> Exit with 99  when we need action

- ha/virsh/README.md
- ha/virsh/create-vm.sh
When setting up the cluster, we have been assuming that all user home directories are in /home/$USER. That is not necessarily true and it is not true for the default root user home which is in /root.
> ha: do not assume all homes are /home/$USER

- ha/virsh/run_tests.sh
When running multiple tests at once, list which ones failed instead of just reporting general failure.
> ha: specify failed tests

- metric-server-simple/metric-server-simple.sh
From Noble onwards, "cloud-init status --wait" can return other than
zero.  The script should only error out if the return code is 1.
@paride, this fixes a problem which has been affecting the Noble
metrics VM for a several days now.  WDYT?
Thanks!
> m/metric-server-simple.sh: Improve handling of "cloud-init status --wait"

- ha/virsh/tests/fence_ipmilan_test.sh
- ha/virsh/vm_utils.sh
This is my idea to replace all the loose sleep calls within our tests.
We implementa an exponential backoff function which evaluates another function passed by the caller. This function result determines whether we want to sleep or not. Each time the function passed by the caller fails, we calculate the new backoff time and sleep again until a maximum number of attempts.
In this first PR, I am only introducing the new function and using the fence_ipmilan test as a case. When this is merged, I will proceed to remove the sleep calls from the other tests.
> ha: add backoff function

- ha/virsh/tests/resource_pgsql_test.sh
To move the pgsql resource agent to main, we moved it to the resource-agents-base package. We now install the base package instead of the extra one so the pgsql agent is properly installed.
> ha: install the pgsql agent from the -base package

- openssh-ccache-check/openssh-ccache-check.py
This adds noble to the openssh-ccache-check script used by the openssh-ccache-check jenkins job.
> openssh ccache: add noble

- git-ubuntu/vm_setup
This is to correspond to the move from core20 to core24, and needs to land at the same time as the corresponding change in git-ubuntu snap packaging.
See also:
https://warthogs.atlassian.net/browse/SD-1202
https://code.launchpad.net/~racb/git-ubuntu/+git/usd-importer/+merge/475008
> git-ubuntu: move from Focal to Noble
