canonical/server-test-scripts

git-ubuntu/vm_setup

Hopefully this will fix the current build problem.

Give git-ubuntu build VM more RAM

---

cloud-init/daily_deb.sh

ctool provides much of the functionality that was used here.
Use it to make things easier.

cloud-init/daily_deb.sh: use ctool.

---

boot-speed/clouds/ec2_cleanup.py
boot-speed/clouds/measure-cloud.py

* refactor measure-cloud.py
* add an EC2 cleanup script

bootspeed: better support for EC2 measurements

---

boot-speed/clouds/measure-cloud.py

* use file timestamps up to the second
* sleep between reboots

bootspeed: better support for multiple runs

---

boot-speed/clouds/measure-cloud.py

Support the Ubuntu release metanames: lts, stable, devel, latest.
They are resolved to actual release names using ubuntu-distro-info(1).

measure-cloud: support the release metanames

---

boot-speed/clouds/measure-cloud.py

This should merge alongside https://github.com/canonical/pycloudlib/pull/9

pycloudlib api changes

---

ubuntu-advantage-client/azure_cleanup.py

Some variable were not updated in the `azure_cleanup` script

Fix azure cleanup script

---

ubuntu-advantage-client/azure_cleanup.py

Emit dots in the stdout when running the `azure_cleanup` scriprt on travis. Right now, we are using the `emit_dots_on_travis` function developed for `cloud-init` here [#347](https://github.com/canonical/cloud-init/pull/347)
An alternative here would be to import this function directly from `cloud-init`, but I don't know if we should assume that `cloud-init`will always be available when running this script

Emit dots when waiting for azure cleanup on travis

---

oci-unit-tests/alertmanager_test.sh

A fired alert scenario was tested, more test cases should be added.

OCI unit test: alertmanager

---

oci-unit-tests/cortex_test.sh
oci-unit-tests/cortex_test_data/cortex.yaml

Check if the expected services are correctly running.

OCI unit test: cortex

---

oci-unit-tests/telegraf_test.sh
oci-unit-tests/telegraf_test_data/telegraf.conf

Check whether:
- telegraf can properly start, and;
- telegraf can be invoked with a custom config file, and can write to
an HTTP endpoint.
More tests should be added later.

OCI unit tests: telegraf

---

ubuntu-advantage-client/gcp_cleanup.py

Add script to clean GCP instances

Add GCP cleanup script

---

ubuntu-advantage-client/ec2_cleanup.py

Currently, we do not check for failures when deleting ec2 resources. This means that we will abort the cleanup
script if we fail to delete any resource. This is not ideal, since we should be trying to cleanup as much as we can on each
run. We are updating the script to do that

Add try except block when deleting ec2 resources

---

oci-unit-tests/postgres_test.sh

This (postgres) is the official name of our OCI image; use it
throughout the test (where applicable, of course).

Rename postgresql to postgres

---

ha/virsh/tests/resource_ipaddr2_test.sh
ha/virsh/tests/resource_systemd_test.sh
ha/virsh/vm_utils.sh

I still want to do some refactoring because there is some duplicated code in `resource_systemd_test.sh` and `resource_ipaddr2_test.sh`. But the logic of the tests is done, any feedback is welcome.

ha/virsh/tests: add tests for the systemd resource agent

---

oci-unit-tests/nginx_test.sh

This partially reverts f46faddec1b62ea5e74383d9c7ebc696b528fe8e,
adding back the creation/removal of DOCKER_NETWORK but using it
only for test_reverse_proxy, where it's actually needed.
For the rationale on why we're not using DOCKER_NETWORK globally see
the f46faddec1b62ea5e74383d9c7ebc696b528fe8e commit message.

OCI nginx: use a dedicated network for test_reverse_proxy

---

ha/virsh/create-vm.sh
ha/virsh/tests/resource_lvm-activate_test.sh

I run it locally and everything is passing.

[HA] Add tests for LVM-activate resource agent

---

ha/virsh/run_tests.sh
ha/virsh/tests/fence_mpath_test.sh

Add some basic tests for the `fence_mpath` agent.

HA: test fence_mpath

---

cloud-init/copr_build.py

The v2 api is broken at the moment [1], and even if fixed it's going to
be turned off due to deprecation in a few months. Let's switch to v3.
[1] https://pagure.io/copr/copr/issue/2003
[2] https://fedora-copr.github.io/posts/EOL-APIv1-APIv2-pt2

copr: switch to the copr api v3

---

oci-unit-tests/prometheus_test.sh

This set of changes ensures prometheus tests are fit to run against all currently published versions of prometheus by considering recent UI changes and output redirections.

oci: prometheus testing improvements

---

ha/virsh/create-vm.sh
ha/virsh/delete-cluster.sh
ha/virsh/run_tests.sh
ha/virsh/tests/fence_sbd_test.sh
ha/virsh/vm_utils.sh

For the moment, I am installing `fence-agents-extra` during the test but it should be removed once `fence_sbd` is added to the `fence-agents-common` binary package.

Test fence sbd

---

ha/virsh/run_tests.sh
ha/virsh/tests/resource_iscsi_target_test.sh

Adding tests for `iSCSITarget` and `iSCSILogicalUnit` resources.

Test iSCSI target resources

---

oci-unit-tests/kafka_test.sh

Signed-off-by: Athos Ribeiro <athos.ribeiro@canonical.com>

OCI: Add kafka unit tests

---

oci-unit-tests/kafka_test.sh

The kafka image was split into a kafka and a zookeeper image. Here, we
adapt the tests to the new images structure.
Signed-off-by: Athos Ribeiro <athos.ribeiro@canonical.com>

Update kafka tests to comply with new structure

---

ha/virsh/README.md
ha/virsh/create-vm.sh
ha/virsh/delete-cluster.sh
ha/virsh/setup-cluster.sh
ha/virsh/tests/fence_mpath_test.sh
ha/virsh/tests/fence_sbd_test.sh
ha/virsh/tests/fence_scsi_test.sh
ha/virsh/tests/fence_virsh_test.sh
ha/virsh/tests/resource_ipaddr2_test.sh
ha/virsh/tests/resource_iscsi_initiator_test.sh
ha/virsh/tests/resource_iscsi_target_test.sh
ha/virsh/tests/resource_lvm-activate_test.sh
ha/virsh/tests/resource_systemd_test.sh
ha/virsh/vm_utils.sh

Update all HA related scripts to use `pcs` instead of `crmsh`.

HA: move to pcs

---

metric-server-bugs/lp-query-gspread

This is a tool from @mclemenceau that I extended to put data into google and here changed it to work with anonymous user and to be in the script directory used for our automation jobs.

Add metric server bugs

---

cloud-init/subiquity_live_server.py

- Adapt from mounts to bsdtar  to extract files from ISO.
- Also avoid kvm -daemonize as Jenkins runners won't have access to the display.
Wrap launch_kvm for first boot in a background thread which writes console log to first-boot-console.log instead of saturating 
stdout with all console boot messages and shutdown messages for system first boot.

cloud-init/subiquity: use bsdtar and avoid kvm -daemonize for jenkins runner

---

metric-server-simple/data2influx.py
metric-server-simple/metric-server-simple.sh

This follows the idea of https://wiki.debian.org/ReleaseGoals/SystemdAnalyzeSecurity.
And while this isn't our major strategy it is very easy to gather, interesting to see the effects of the Debian effort and something that we do not want to regress even if not a major mission.

metric add service-security

---

openssh-ccache-check/README.txt
openssh-ccache-check/openssh-ccache-check.py

This will be called by a jenkins job.

Add openssh-ccache-check script and README

---

openssh-ccache-check/openssh-ccache-check.py

If there is action needed, print out the specification number for reference.

Add reference to spec US066

---

cpc/README.md
cpc/aws/amazon-ec2-net-utils/README.md
cpc/aws/amazon-ec2-net-utils/delete-vpc-and-subnets.sh
cpc/aws/amazon-ec2-net-utils/pre-create-vpc-and-subnets.sh
cpc/aws/amazon-ec2-net-utils/run-tests.sh
cpc/aws/amazon-ec2-net-utils/test-amazon-ec2-net-utils.sh

These tests are very much still WIP, but I'd like to see if it's fine for me to store this test script in this repo. I'm also thinking about adding my `ec2-hibinit-agent` test to this repo. These are cloud specific packages, but I think it makes sense to store them in this repository for now until there are enough cloud packages.
Alternatively I could add the cloud packages into a `./cloud/` or `./cpc/` directory. This way it'd be easy to find the test scripts from both the cpc/server team.
thoughts?

amazon-ec2-net-utils: init commit

---

ha/virsh/README.md

The current README.md file instructions are outdated and missing information. This patch updates it so a reader can easily run tests and debug issues within a local environment.

ha: update documentation

---

ha/virsh/tests/resource_pgsql_test.sh
ha/virsh/vm_utils.sh

* Prepare for codebase for promotion to main
* Support different postgresql versions

ha: adjust pgsql tests for different series

---

ha/virsh/tests/fence_ipmilan_test.sh
ha/virsh/vm_utils.sh

This is a first PR for fixing some of the failing or flaky HA tests.
This first one focus on ipmilan, which is failing (not flaky).
I will follow-up soon with changes to the sleeps around the code so we can improve the test flakiness as well (I will probably add a single function with a back-off factor to deal with the issue).

ha: Fix ipmilan failing tests
